name: 'Lerna release action: Version'
description: 'Action to version selected packages'
inputs:
  github-token:
    description: 'Token used to create a PR'
    required: true
  packages:
    description: 'Selected packages as comma separated string, e.g. modules/storage-spec,libraries/formatting'
    required: true
  version-strategy:
    description: 'Versioning strategy, supports conventional-commits and static versioning through: patch, minor, major, premajor, preminor, prepatch, prerelease'
    default: 'conventional-commits'
  version-extra-args:
    description: 'Additional args appended to the lerna version call'
  assignee:
    description: 'User to assign the workflow to. When triggered through workflow_dispatch, this will default to the user who invoked the workflow.'
  committer:
    description: 'User creating the commit, defaults to the assignee'
    required: false
  auto-merge:
    description: 'Enables auto-merging on the created pull request when set to `true`. Defaults to `false`.'
    default: false
  request-reviewers:
    description: 'Request PR assignees as reviewers'
    default: true
  draft:
    description: 'Creates the release PR as draft'
    default: false

runs:
  using: 'node20'
  main: '../dist/version/index.js'
author: 'ExodusMovement'
branding:
  icon: 'plus-square'
  color: 'blue'
