name: 'Lerna release action: Publish'
description: 'Action to publish yet unpublished packages'
inputs:
  github-token:
    description: 'Token used to create a PR'
    required: true


runs:
  using: 'node16'
  main: '../dist/publish/index.js'
author: 'ExodusMovement'
branding:
  icon: 'upload-cloud'
  color: 'purple'
