name: 'Lerna release action: Version Dispatch'
description: 'Action to trigger the versioning process post-merge'
inputs:
  github-token:
    description: 'Token used to create a PR'
    required: true
  ref:
    description: 'Ref to checkout'
    default: 'master'
  exclude-commit-types:
    description: 'Specify any commit types that should not trigger versioning'
    default: 'docs,chore'
  exclude-labels:
    description: 'Specify any labels that should not trigger versioning'
    default: 'skip-release'
  version-workflow-id:
    description: 'ID of the version workflow'
    default: 'version.yml'
runs:
  using: 'node20'
  main: '../dist/version-dispatch/index.js'
author: 'ExodusMovement'
branding:
  icon: 'plus-square'
  color: 'blue'
