name: 'Checks'
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Grant read access to private registry
        run: yarn config set --home 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Format
        run: yarn format:check
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Checked in build?
        run: git diff --exit-code
      - name: Lint
        run: yarn lint
